server:
  port: 9092
  servlet:
    context-path: '/mentesa/'

spring:
  application:
    name: mentesa
#  profiles: local
  datasource:

      #local/:
      url:  jdbc:postgresql://localhost:5432/menteSaLocal
      username: postgres
      password: admin

#    prod/:
#    url:  jdbc:postgresql://db-instance-happy-alert.covvdf22qdcg.us-east-1.rds.amazonaws.com:5432/postgres?currentSchema=sch_mentesa
#    username: postgres
#    password: teste123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      default_schema: sch_mentesa
    properties:
      hibernate:
        show_sql: true
        format_sql: true



#server:
#  port: 9092
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 200mb
#      max-request-size: 215mb
#    context-path: /mentesa-java
#spring:
#  application:
#    name: mentesa-java
#  profiles:
#    active: dev
#
#---
#spring:
#  profiles: local
#  datasource:
#    driver-class-name:
#    url: jdbc:postgresql://db-instance-happy-alert.covvdf22qdcg.us-east-1.rds.amazonaws.com:5432/postgres?currentSchema=sch_mentesa
#    username: postgres
#    password: teste123
#  jpa:
#    ddl-auto: validade
#    default_schema: sch_mentesa
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        temp:
#          use_jdbc_metadata_defaults: false
